application: rms-gadget
version: 1
runtime: python27
api_version: 1

handlers:
- url: /manifests
  static_dir: manifests
  expiration: 1m

- url: /gadgets
  static_dir: gadgets
  expiration: 1m

- url: /css
  static_dir: css
  expiration: 1m
